import type { GadgetModel } from "gadget-server";

// This file describes the schema for the "shopifyShop" model, go to https://soof-s.gadget.app/edit to view/edit your model in Gadget
// For more information on how to update this file http://docs.gadget.dev

export const schema: GadgetModel = {
  type: "gadget/model-schema/v1",
  storageKey: "DataModel-Shopify-Shop",
  fields: {
    chatSessions: {
      type: "hasMany",
      children: { model: "chatSession", belongsToField: "shop" },
      storageKey: "iIxHvSqeQcYA",
    },
    chatbot: {
      type: "hasOne",
      child: { model: "chatbot", belongsToField: "shop" },
      storageKey: "rXvcyzblFCO3",
    },
    exactOnline: {
      type: "hasOne",
      child: {
        model: "integrations/exactOnline",
        belongsToField: "shop",
      },
      storageKey: "7kv1A-cWaJ_J",
    },
    knowledge: {
      type: "hasOne",
      child: { model: "knowledge", belongsToField: "shop" },
      storageKey: "iqjoa5YgWNN3",
    },
    mantleApiToken: { type: "string", storageKey: "Az23x9TxdxEE" },
    plan: {
      type: "hasOne",
      child: { model: "plan", belongsToField: "shop" },
      storageKey: "_iPesn5bBk0e",
    },
  },
  shopify: {
    fields: [
      "address1",
      "address2",
      "checkoutApiSupported",
      "city",
      "collections",
      "cookieConsentLevel",
      "country",
      "countryCode",
      "countryName",
      "countyTaxes",
      "currency",
      "customerAccountsV2",
      "customerEmail",
      "domain",
      "eligibleForCardReaderGiveaway",
      "eligibleForPayments",
      "email",
      "enabledPresentmentCurrencies",
      "finances",
      "forceSsl",
      "fulfillments",
      "gdprRequests",
      "googleAppsDomain",
      "googleAppsLoginEnabled",
      "hasDiscounts",
      "hasGiftCards",
      "hasStorefront",
      "ianaTimezone",
      "latitude",
      "longitude",
      "marketingSmsContentEnabledAtCheckout",
      "moneyFormat",
      "moneyInEmailsFormat",
      "moneyWithCurrencyFormat",
      "moneyWithCurrencyInEmailsFormat",
      "multiLocationEnabled",
      "myshopifyDomain",
      "name",
      "orders",
      "passwordEnabled",
      "phone",
      "planDisplayName",
      "planName",
      "preLaunchEnabled",
      "primaryLocale",
      "productImages",
      "productOptions",
      "productVariants",
      "products",
      "province",
      "provinceCode",
      "requiresExtraPaymentsAgreement",
      "setupRequired",
      "shopOwner",
      "shopifyCreatedAt",
      "shopifyUpdatedAt",
      "source",
      "syncs",
      "taxShipping",
      "taxesIncluded",
      "timezone",
      "transactionalSmsDisabled",
      "weightUnit",
      "zipCode",
    ],
  },
};
